- README.md
- small changes to Development & Deployments section
- mention deployed namespace at top, link up GraphiQL for each deployment
> dev instructions tweaks

- src/helpers.ts
- src/mappings/dtfactory.ts
Related to https://github.com/oceanprotocol/multi-repo-issue/issues/82
Added correct ocean token address.
> Update ocean address

- schema.graphql
- src/mappings/datatoken.ts
> add block to dt orders

- src/mappings/pool.ts
Closes #116 
-  fix decimal maths
- 
-
> fix decimal math

- .docignore
- README.md
Fixes # .
- Center align the links for better UI in read-the-docs.
> Feature: Improve readme file for rendering in read-the-docs

- src/helpers.ts
Proper use of debug instead of info
> Use debug instead of info

- README.md
Fixes #167 .
- Add subgraph links for Polygon and Bsc networks
> Feature: add Ploygon and Bsc in supported networks

- schema.graphql
- src/mappings/fixedrateexchange.ts
- subgraph.bsc.yaml
- subgraph.gaiaxtestnet.yaml
- subgraph.moonbeamalpha.yaml
- subgraph.mumbai.yaml
- subgraph.polygon.yaml
- subgraph.rinkeby.yaml
- subgraph.ropsten.yaml
- subgraph.yaml
- test/integration/Datatokens.test.ts
> Added baseTokenSymbol to FixedRateExchange

- schema.graphql
Added fixedRateExchanges, pools and dispensers on token
> schema updates

- schema.graphql
- src/mappings/erc20Templates.ts
- src/mappings/nftUpdate.ts
> add nft.orderCount

- schema.graphql
- scripts/generatenetworkssubgraphs.js
- src/mappings/dispenser.ts
- src/mappings/fixedRateExchange.ts
- src/mappings/utils/dispenserUtils.ts
- src/mappings/utils/fixedRateUtils.ts
Closes #310 
Closes #340 
- refactor exchangeId: FixedRateExchange!  to account contract address as well
> add fixedrate balances

- src/mappings/dispenser.ts
- src/mappings/utils/dispenserUtils.ts
> dispenser updates

- package-lock.json
- src/mappings/erc721Factory.ts
- src/mappings/fixedRateExchange.ts
- src/mappings/pool.ts
- src/mappings/utils/poolUtils.ts
- subgraph.yaml
Fixes https://github.com/oceanprotocol/ocean-subgraph/issues/356  https://github.com/oceanprotocol/ocean-subgraph/issues/312
> Fix poolSnapshot and fixed rate balance

- src/mappings/nftUpdate.ts
> fix nft on updates

- src/mappings/pool.ts
- subgraph.yaml
> fix poolSnapshot

- src/mappings/pool.ts
> fix liquidity

- docker/README.md
- schema.graphql
- src/mappings/pool.ts
- src/mappings/utils/poolUtils.ts
> fix pool exit values

- .github/workflows/tests.yml
- package-lock.json
- package.json
- schema.graphql
- src/mappings/erc721Factory.ts
- src/mappings/pool.ts
- subgraph.template.yaml
- test/integration/SimplePublishConsume.test.ts
> bump contracts to alpha28 and ocean.js to alpha 33

- README.md
> Fix README subgraph links

- package-lock.json
- package.json
> bump ocean.js & add polygon

- schema.graphql
- src/mappings/factoryRouter.ts
Fixes #433 
- Renaming consumeFee to orderFee
> Renaming consumeFee to orderFee

- package-lock.json
- package.json
> bump to ocean.js 44

- package-lock.json
- package.json
> latest contracts&ocean.js

- schema.graphql
> OPC Approved tokens: store as token, not only address

- src/mappings/factoryRouter.ts
Fixes #465 
```
{
"data": {
"opcs": [
{
"approvedTokens": [
{
"id": "0x282d8efce846a88b159800bd4130ad77443fa1a1",
"name": "Ocean Token (PoS)",
"symbol": "mOCEAN",
"decimals": 18
},
{
"id": "0xc5248aa0629c0b2d6a02834a5f172937ac83cbd3",
"name": "H20data",
"symbol": "H20",
"decimals": 18
}
]
}
],
}
```
> Fix approved tokens

- package.json
- schema.graphql
- scripts/replaceVersion.js
- src/mappings/utils/globalUtils.ts
update version on release and then write it in global stats on deploy
> Add version in global stats

- schema.graphql
Fixes #476 
- changing `lastPriceToken` from token to string
> Fixing lastPriceToken

- .vscode/extensions.json
- .vscode/settings.json
- schema.graphql
- src/mappings/erc20Templates.ts
- src/mappings/utils/orderUtils.ts
- subgraph.template.yaml
- test/integration/SimplePublishConsume.test.ts
Fixes #471 
- Tracking providerFee event
- Saving providerFee as a string inside order
- Creating orderUtils.ts
> Issue 471 provider fees

- README.md
- Removing Pool example queries from Readme
- Adding new example queries
- Minor formatting
> Removing Pool example queries and adding new examples

- package-lock.json
- package.json
- schema.graphql
- src/mappings/utils/veUtils.ts
- src/mappings/veOCEAN.ts
- test/integration/Datatoken.test.ts
- test/integration/Dispenser.test.ts
- test/integration/FixedRateExchange.test.ts
- test/integration/Nft.test.ts
- test/integration/SimplePublishConsume.test.ts
- test/integration/SimpleSubgraph.test.ts
- test/integration/VeOcean.test.ts
- test/integration/users.test.ts
- bump ocean-lib to 2.0.0-next.3
- update tests
> update tests for new ocean.js 2.0

- schema.graphql
- src/mappings/nftUpdate.ts
- subgraph.template.yaml
- test/integration/Nft.test.ts
> add erc725 key/value store

- src/mappings/nftUpdate.ts
> fix nftUpdate critical bug

- package.json
> add goerli npm command

- src/mappings/factoryRouter.ts
- test/integration/FactoryRouter.test.ts
> fix tokenRemoved

- package.json
- schema.graphql
- src/mappings/erc20Templates.ts
- src/mappings/erc721Factory.ts
- src/mappings/nftUpdate.ts
- test/integration/Datatoken.test.ts
- test/integration/Dispenser.test.ts
- test/integration/FixedRateExchange.test.ts
- test/integration/Nft.test.ts
- test/integration/SimplePublishConsume.test.ts
- test/integration/SimpleSubgraph.test.ts
Fixes #570 
- Tracking `NftTransferHistory`
- Updating `creator`, `owner` and `transferHistory` in `Order`
- Updating tests
> nft transfer event

- schema.graphql
- src/mappings/veOCEAN.ts
> fix veDeposit id generation

- package-lock.json
- package.json
- test/integration/Datatoken.test.ts
- test/integration/Nft.test.ts
- test/integration/SimplePublishConsume.test.ts
- fix tests
- update oceanjs version in `package.json`
> Update ocean-lib with 2.7.0 version.

- schema.graphql
- src/mappings/utils/veUtils.ts
- src/mappings/veDelegation.ts
- test/integration/VeOcean.test.ts
Fixes #645
Fixes #646
- Removing `amountFraction` 
- adding `timestamp`
> Removing amountFraction and adding timestamp

- subgraph_ve.template.yaml
- add missing events in subgraph , since we already have the handlers
> add events handlers

- package-lock.json
- package.json
> bump to latest contracts

- docker/docker-compose.yml
> Bump to graphnode 0.28.2

- .github/workflows/tests.yml
- package-lock.json
- package.json
- schema.graphql
- src/mappings/factoryRouter.ts
- src/mappings/utils/fixedRateUtils.ts
- subgraph.template.yaml
- test/integration/FixedRateExchange.test.ts
- test/integration/users.test.ts
- Closes #739
- bump contracts to v2.0.3
- fix fixedrate tests (added withMint & active states when fre is created, updated flows)
- test with graph-node v0.33.0
> Feature/add_optimism & use graph-node 0.33.0

- README.md
- deployment/README.md
- package.json
- src/mappings/erc20Template3.ts
When a slot status is changed to "Canceled" in payout function, we don't update the corresponding predictoorSlot.
This PR add logic to fix this issue
> fix missing logic
